### ISSUE TITLE
KeyError: 'link'

### ISSUE THREAD

**Issue by dbarzin** [pandora-analysis/pypandora#8]
Got an error while submitting a file to Pandora with pypandora :

$ poetry run pandora --url http://127.0.0.1:6100 -f ./test

Traceback (most recent call last):
  File "/home/pandora/.local/bin/pandora", line 8, in <module>
    sys.exit(main())
  File "/home/pandora/.local/lib/python3.10/site-packages/pypandora/__init__.py", line 39, in main
    response = client.submit_from_disk(args.file, seed_expire=3600)
  File "/home/pandora/.local/lib/python3.10/site-packages/pypandora/api.py", line 69, in submit_from_disk
    return self.submit(file_in_memory, filename, seed_expire)
  File "/home/pandora/.local/lib/python3.10/site-packages/pypandora/api.py", line 101, in submit
    to_return['link'] = urljoin(self.root_url, to_return['link'])
KeyError: 'link'

This is due to the fact that the returned JSON from Pandora is :

{'success': False, 'error': None}

and does not contains 'link' key.

**Comment by Rafiot** [comment]
Right, I need to catch that on the client side, but it also means that the web service raises an exception. And in theory, the error key should have a message (which it doesn't, annoyingly).

I'm going to add a logging stacktrace to log that one so we have a chance to figure out what the issue is.
