### ISSUE TITLE
local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by dbarzin** [pandora-analysis/pypandora#9]
Got this error while trying to run pypandora :

    $ poetry run pandora --url http://127.0.0.1:6100 -f ./LICENSE
    {
      "success": true,
      "taskId": "d9c80db1-b086-43cd-ada7-03ec528a711d",
      "seed": "nVV54O6abmC-Pdy3dT_0WkRlyivB0jGcsnrsvMUEcys",
      "lifetime": 3600,
      "link": "http://127.0.0.1:6100/analysis/d9c80db1-b086-43cd-ada7-03ec528a711d/seed-nVV54O6abmC-Pdy3dT_0WkRlyivB0jGcsnrsvMUEcys"
    }

    $ poetry run pandora --url http://127.0.0.1:6100 --seed nVV54O6abmC-Pdy3dT_0WkRlyivB0jGcsnrsvMUEcys
    Traceback (most recent call last):
      File "/home/pandora/.local/bin/pandora", line 8, in <module>
        sys.exit(main())
      File "/home/pandora/.local/lib/python3.10/site-packages/pypandora/__init__.py", line 40, in main
        print(json.dumps(response, indent=2))
    UnboundLocalError: local variable 'response' referenced before assignment
    pandora@pandora:~/pandora$ poetry run pandora --url http://127.0.0.1:6100 --task_id "d9c80db1-b086-43cd-ada7-03ec528a711d"
    Traceback (most recent call last):
      File "/home/pandora/.local/bin/pandora", line 8, in <module>
        sys.exit(main())
      File "/home/pandora/.local/lib/python3.10/site-packages/pypandora/__init__.py", line 40, in main
        print(json.dumps(response, indent=2))
    UnboundLocalError: local variable 'response' referenced before assignment

**Comment by Rafiot** [comment]
I should also mark these two as required.
